Workflows

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -36,6 +36,52 @@ jobs:
     - name: Build with Gradle Wrapper
       run: ./gradlew build dokkaGenerate
 
+
+      run: |
+            INSTANCE=${INSTANCE#*/}
+            INSTANCE_ID_UPPER=$(echo "$INSTANCE" | tr '[:lower:]' '[:upper:]')
+            ARTIFACT="webHelp${INSTANCE_ID_UPPER}2-all.zip"
+            ALGOLIA_ARTIFACT="algolia-indexes-${INSTANCE_ID_UPPER}.zip"
+            
+            # Print the values
+            echo "INSTANCE_ID_UPPER: $INSTANCE_ID_UPPER"
+            echo "ARTIFACT: $ARTIFACT"
+            echo "ALGOLIA_ARTIFACT: $ALGOLIA_ARTIFACT"
+            
+            # Set the environment variables and outputs
+            echo "INSTANCE_ID_UPPER=$INSTANCE_ID_UPPER" >> $GITHUB_ENV
+            echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
+            echo "ALGOLIA_ARTIFACT=$ALGOLIA_ARTIFACT" >> $GITHUB_ENV
+            echo "artifact=$ARTIFACT" >> $GITHUB_OUTPUT
+            echo "algolia_artifact=$ALGOLIA_ARTIFACT" >> $GITHUB_OUTPUT
+
+        - name: Copy Dokka HTML to Writerside
+          run: |
+            mkdir -p Writerside/api-docs
+            if [ -d "api/build/dokka/html" ]; then
+              cp -rv api/build/dokka/html/* Writerside/api-docs/
+            else
+              echo "Dokka output directory not found!"
+              exit 1
+            fi
+
+        - name: Build docs using Writerside Docker builder
+          uses: JetBrains/writerside-github-action@v4
+          with:
+            instance: ${{ env.INSTANCE }}
+            docker-version: ${{ env.DOCKER_VERSION }}
+
+        - name: Save artifact with build results
+          uses: actions/upload-artifact@v4
+          with:
+            name: docs
+            path: |
+              artifacts/${{ steps.define-ids.outputs.artifact }}
+              artifacts/report.json
+              artifacts/${{ steps.define-ids.outputs.algolia_artifact }}
+            retention-days: 7
+
+
   dependency-submission:
 
     runs-on: ubuntu-latest
@@ -52,64 +98,6 @@ jobs:
 
     - name: Generate and submit dependency graph
       uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
-
-
-  rebuild:
-    runs-on: ubuntu-latest
-    outputs:
-      algolia_artifact: ${{ steps.define-ids.outputs.algolia_artifact }}
-      artifact: ${{ steps.define-ids.outputs.artifact }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Define instance id and artifacts
-        id: define-ids
-        run: |
-          INSTANCE=${INSTANCE#*/}
-          INSTANCE_ID_UPPER=$(echo "$INSTANCE" | tr '[:lower:]' '[:upper:]')
-          ARTIFACT="webHelp${INSTANCE_ID_UPPER}2-all.zip"
-          ALGOLIA_ARTIFACT="algolia-indexes-${INSTANCE_ID_UPPER}.zip"
-
-          # Print the values
-          echo "INSTANCE_ID_UPPER: $INSTANCE_ID_UPPER"
-          echo "ARTIFACT: $ARTIFACT"
-          echo "ALGOLIA_ARTIFACT: $ALGOLIA_ARTIFACT"
-
-          # Set the environment variables and outputs
-          echo "INSTANCE_ID_UPPER=$INSTANCE_ID_UPPER" >> $GITHUB_ENV
-          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
-          echo "ALGOLIA_ARTIFACT=$ALGOLIA_ARTIFACT" >> $GITHUB_ENV
-          echo "artifact=$ARTIFACT" >> $GITHUB_OUTPUT
-          echo "algolia_artifact=$ALGOLIA_ARTIFACT" >> $GITHUB_OUTPUT
-
-      - name: Copy Dokka HTML to Writerside
-        run: |
-          mkdir -p Writerside/api-docs
-          if [ -d "api/build/dokka/html" ]; then
-            cp -rv api/build/dokka/html/* Writerside/api-docs/
-          else
-            echo "Dokka output directory not found!"
-            exit 1
-          fi
-
-      - name: Build docs using Writerside Docker builder
-        uses: JetBrains/writerside-github-action@v4
-        with:
-          instance: ${{ env.INSTANCE }}
-          docker-version: ${{ env.DOCKER_VERSION }}
-
-      - name: Save artifact with build results
-        uses: actions/upload-artifact@v4
-        with:
-          name: docs
-          path: |
-            artifacts/${{ steps.define-ids.outputs.artifact }}
-            artifacts/report.json
-            artifacts/${{ steps.define-ids.outputs.algolia_artifact }}
-          retention-days: 7
 
   test:
     needs: build
